# Change these first
owner: fraserbooth # Your GitHub username
repo: fb-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: OptBP Site
    url: http://www.optbp.com/
  - name: Remote Check In Site
    url: https://remote-check-in.github.io/rci-site/
  - name: Remote Check In Site
    url: https://remote-check-in.github.io/rci-site/
  - name: Palma
    url: https://www.comebacktopalma.info/
  - name: UAT Pt
    url: http://optimise-bp-patient-uat.azurewebsites.net/
  - name: UAT Clin
    url: https://optimise-bp-clinician-uat.azurewebsites.net/
  - name: UAT Auth
    url: https://optimise-bp-auth-uat.azurewebsites.net/Account/LoginWithPasscode
  - name: Aura-Soma
    url: https://www.aura-soma.com/
  - name: AEOS
    url: https://www.aeos.net/
  - name: ShireFarm
    url: https://www.shirefarm.co.uk/
  - name: Pegasus
    url: http://www.pegasus-parfum.com/



status-website:
  #cname: monitor.optbp.com
  baseUrl: /fb-monitor
  logoUrl: https://optimise-bp-auth-uat.azurewebsites.net/images/logo-icon.png
  name: Frasers Monitor
  introTitle: "Welcome to the Status Page."
  introMessage: This status page uses **real-time** data from our server.
  #navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
