# Change these first
owner: fraserbooth # Your GitHub username
repo: fb-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: OptBP Site
    url: http://www.optbp.com/
  - name: Remote Check In Site
    url: https://www.remotecheckin.co.uk/
  - name: OptBP Pt
    url: http://pt.optbp.com/
  - name: OptBP Clin
    url: https://clin.optbp.com/
  - name: OptBP Auth
    url: https://auth.optbp.com/Account/LoginWithPasscode
  - name: OptBP API
    url: https://api.optbp.com/api/practice/additionaldetails/
  - name: Hangfire
    url: https://api.optbp.com/hangfire
    expectedStatusCodes:
      - 401
  - name: Palma
    url: https://www.comebacktopalma.info/
  - name: Aura-Soma
    url: https://www.aura-soma.com/
  - name: AEOS
    url: https://www.aeos.net/
  - name: ShireFarm
    url: https://www.shirefarm.co.uk/
  - name: Pegasus
    url: http://www.pegasus-parfum.com/



status-website:
  #cname: monitor.optbp.com
  baseUrl: /fb-monitor
  logoUrl: https://optimise-bp-auth-uat.azurewebsites.net/images/logo-icon.png
  name: Frasers Monitor
  introTitle: "Welcome to the Status Page."
  introMessage: This status page uses **real-time** data from our server.
  #navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
