# Change these first
owner: fraserbooth # Your GitHub username
repo: fb-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: UAT Pt
    url: http://optimise-bp-patient-uat.azurewebsites.net/
  - name: UAT Clin
    url: https://optimise-bp-clinician-uat.azurewebsites.net/
  - name: UAT Auth
    url: https://optimise-bp-auth-uat.azurewebsites.net/Account/LoginWithPasscode

status-website:
  #cname: monitor.optbp.com
  baseUrl: /fb-monitor
  logoUrl: https://optimise-bp-auth-uat.azurewebsites.net/images/logo-icon.png
  name: Frasers Monitor
  introTitle: "Welcome to the Status Page."
  introMessage: This status page uses **real-time** data from our server.
  #navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
